abbr tls 'tmux list-sessions'
abbr tas 'tmux attach-session -t'
abbr tns 'tmux new-session -s'
abbr tks 'tmux kill-session -t'
abbr tka 'tmux kill-server'

abbr gin 'git init'
abbr gst 'git status'
abbr glg 'git log'
abbr gcl 'git clone'
abbr gada 'git add --all'
abbr gadu 'git add --update'
abbr gcm 'git commit'
abbr gcmm 'git commit --message'
abbr gcma 'git commit --amend'
abbr gfe 'git fetch'
abbr gpl 'git pull'
abbr gps 'git push'
abbr gbr 'git branch'
abbr gco 'git checkout'
abbr gsw 'git switch'
abbr gswc 'git switch --create'
abbr grs 'git restore'
abbr gsh 'git stash'
abbr gshl 'git stash list'
abbr gshp 'git stash pop'

abbr bls 'brew list'
abbr bis 'brew install'
abbr bus 'brew uninstall'
abbr bup 'brew update'
abbr bug 'brew upgrade'
abbr bcl 'brew cleanup'

abbr dot 'git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
abbr lazydot 'lazygit -g=$HOME/.dotfiles/ -w=$HOME'
